### ISSUE TITLE
Feature: User can view a list of ghibli films

### ISSUE THREAD

**Issue by jonathan-byun** [jonathan-byun/ghibli-journal#1]
## ⚙️ Feature

> ##### able to see all ghibli films and select on them to view them individually

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] create a headerbar that contains links to each view
- [ ] add form for search in headerbar
- [ ] create a new div and list to contain all the movies
- [ ] create a sample movie block to get formatting
- [ ] import movie title poster and rating from api and local storage
- [ ] create dom tree and append it to the list
- [ ] 
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
