### ISSUE TITLE
Feature: User can View the details of a film

### ISSUE THREAD

**Issue by jonathan-byun** [jonathan-byun/ghibli-journal#2]
## ⚙️ Feature

> Users can click on the link of the film title name to see the single film page of the title

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] Add movie title, poster img, and description texts
- [ ] add button for rating that prompts a modal on click
- [ ] add characters list
- [ ] populate characters list with characters from api that are in the film
- [ ] each character name should be a link that takes the user to single character page on click
- [ ] add vehicles list with the same properties as the characters list
- [ ] add comments text area and submission
- [ ] add previous comments stored in local storage
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
