### ISSUE TITLE
Feature: User can rate a film out of 10

### ISSUE THREAD

**Issue by jonathan-byun** [jonathan-byun/ghibli-journal#3]
## ⚙️ Feature

> user will be able to click on the rate button and fill out a modal for rating the film

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [x] When rating button is clicked on the single films page a modal should appear
- [x] modal should prompt user to select rating
- [x] add drop down input and submit button
- [x] make it so when user clicks out of the modal box they exit the modal
- [x] save the new rating if it is submitted
- [x] update the displayed rating on the movie page
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
